
name: CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    name : Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install || echo "No dependencies to install"

      - name: Run linter
        run: npm run lint || echo "No linter"

      - name: Run tests
        run: npm test || echo "No tests"

      - name: Build project
        run: npm run build || echo "No build"

